// Managed by Xotiic Upload. Only complete releases are shown publicly.
window.XOTIICDUCK_RELEASES = [
  {
    "id": "void-crown-treasury",
    "title": "Void Crown Treasury",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 306,
    "audio": "music/void-crown-treasury.mp3",
    "cover": "covers/void-crown-treasury.png",
    "status": "published"
  },
  {
    "id": "beyond-the-last-tomorrow",
    "title": "Beyond The Last Tomorrow",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 480,
    "audio": "music/beyond-the-last-tomorrow.mp3",
    "cover": "covers/beyond-the-last-tomorrow.png",
    "status": "published"
  },
  {
    "id": "silent-storm",
    "title": "Silent Storm",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 418,
    "audio": "music/silent-storm.mp3",
    "cover": "covers/silent-storm.png",
    "status": "published"
  },
  {
    "id": "ghost-of-the-uchiha",
    "title": "Ghost Of The Uchiha",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 326,
    "audio": "music/ghost-of-the-uchiha.mp3",
    "cover": "covers/ghost-of-the-uchiha.png",
    "status": "published"
  },
  {
    "id": "storm-dragon-unleashed",
    "title": "Storm Dragon Unleashed",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 332,
    "audio": "music/storm-dragon-unleashed.mp3",
    "cover": "covers/storm-dragon-unleashed.png",
    "status": "published"
  },
  {
    "id": "tempest-garage",
    "title": "Tempest Garage",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 345,
    "audio": "music/tempest-garage.mp3",
    "cover": "covers/tempest-garage.png",
    "status": "published"
  },
  {
    "id": "misfit-crown",
    "title": "Misfit Crown",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 315,
    "audio": "music/misfit-crown.mp3",
    "cover": "covers/misfit-crown.png",
    "status": "published"
  },
  {
    "id": "rise",
    "title": "Rise",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 282,
    "audio": "music/rise.mp3",
    "cover": "covers/rise.png",
    "status": "published",
    "lyrics": "[Intro]\nFrom another world, I opened my eyes\nA tiny blue spark under foreign skies\nA voice in my soul began to rise\nGreat Sage, guide me through the night\n\n[Verse 1]\nI woke as a slime where the wild winds roam\nCold cave walls became my home\nThen thunder laughed from a prison of stone\nVeldora, the storm, stood alone\n\nWe traded names beneath the dark\nTempest burned like a newborn mark\nA dragon’s vow and a slime’s first start\nTwo souls carrying one fierce heart\n\n[Pre-Chorus]\nI swallowed the fear, I learned to transform\nTurned every scar into shelter from storms\nFrom weakest of legends to ruler reborn\nI’ll build tomorrow with these hands\n\n[Chorus]\nRise, Tempest, rise\nLet the banners touch the sky\nFor every monster cast aside\nI’ll be the name they call with pride\n\nShine, silver light\nMask of fate and demon eyes\nFrom slime to king, from dusk to dawn\nRimuru Tempest carries on\n\n[Verse 2]\nShizu’s flame was fading slow\nA hero’s sorrow I came to know\nHer mask, her wish, her gentle glow\nBecame the face I’d never throw\n\nGoblin, wolf, ogre, kijin flame\nI gave them hope, I gave them names\nIn Jura’s forest we rose the same\nA nation born from bonds, not chains\n\n[Pre-Chorus]\nBenimaru’s fire, Shuna’s prayer\nSouei moving through midnight air\nShion’s blade and Ranga’s glare\nAll of Tempest standing there\n\n[Chorus]\nRise, Tempest, rise\nLet the banners touch the sky\nFor every monster cast aside\nI’ll be the name they call with pride\n\nShine, silver light\nMask of fate and demon eyes\nFrom slime to king, from dusk to dawn\nRimuru Tempest carries on\n\n[Post-Chorus]\nOh-oh, Great Sage awaken\nOh-oh, Raphael calling\nOh-oh, my vow unshaken\nTempest will rise\n\n[Verse 3]\nWhen my people fell, the sky went still\nMercy bent beneath my will\nMegiddo rained with judgment’s chill\nA king must guard what monsters built\n\nThe Harvest came with crimson light\nTen thousand souls crossed into night\nA Demon Lord opened his eyes\nAnd Raphael answered from inside\n\n[Bridge]\nGluttony roars, Beelzebuth devours\nUriel shields my promised towers\nVeldora’s storm becomes my power\nI stand for peace in the darkest hour\n\nI’ll face the saints, the lords, the throne\nThe world may test the path I own\nBut every soul that calls Tempest home\nWill never stand alone\n\n[Final Chorus]\nRise, Tempest, rise\nLet the banners touch the sky\nFor every monster cast aside\nI’ll be the name they call with pride\n\nShine, silver light\nMask of fate and demon eyes\nFrom slime to king, from dusk to dawn\nRimuru Tempest carries on\n\n[Outro]\nFrom a cave to a kingdom bright\nFrom a slime to a storm in flight\nIf this world wants peace, I’ll be the light\nRimuru Tempest, born to unite"
  },
  {
    "id": "earthquake",
    "title": "Earthquake",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 447,
    "audio": "music/earthquake.mp3",
    "cover": "covers/earthquake.png",
    "status": "published"
  },
  {
    "id": "the-little-world-queen",
    "title": "The Little World Queen",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 298,
    "audio": "music/the-little-world-queen.mp3",
    "cover": "covers/the-little-world-queen.png",
    "status": "published"
  },
  {
    "id": "sleeping-ruler",
    "title": "Sleeping Ruler",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 290,
    "audio": "music/sleeping-ruler.mp3",
    "cover": "covers/sleeping-ruler.png",
    "status": "published"
  },
  {
    "id": "twilight-valentine",
    "title": "Twilight Valentine",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 337,
    "audio": "music/twilight-valentine.mp3",
    "cover": "covers/twilight-valentine.png",
    "status": "published"
  },
  {
    "id": "platinum-fallen",
    "title": "Platinum Fallen",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 300,
    "audio": "music/platinum-fallen.mp3",
    "cover": "covers/platinum-fallen.png",
    "status": "published"
  },
  {
    "id": "starborn-catastrophe",
    "title": "Starborn Catastrophe",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 432,
    "audio": "music/starborn-catastrophe.mp3",
    "cover": "covers/starborn-catastrophe.png",
    "status": "published"
  },
  {
    "id": "red-fang-promise",
    "title": "Red Fang Promise",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 396,
    "audio": "music/red-fang-promise.mp3",
    "cover": "covers/red-fang-promise.png",
    "status": "published"
  },
  {
    "id": "crimson-axis",
    "title": "Crimson Axis",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 343,
    "audio": "music/crimson-axis.mp3",
    "cover": "covers/crimson-axis.png",
    "status": "published"
  },
  {
    "id": "oath-of-noir",
    "title": "Oath Of Noir",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 316,
    "audio": "music/oath-of-noir.mp3",
    "cover": "covers/oath-of-noir.png",
    "status": "published"
  },
  {
    "id": "violet-verdict",
    "title": "Violet Verdict",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 319,
    "audio": "music/violet-verdict.mp3",
    "cover": "covers/violet-verdict.png",
    "status": "published"
  },
  {
    "id": "gold-collapse",
    "title": "Gold Collapse",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 346,
    "audio": "music/gold-collapse.mp3",
    "cover": "covers/gold-collapse.png",
    "status": "published"
  },
  {
    "id": "white-crown-scarlet-lake",
    "title": "White Crown, Scarlet Lake",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 310,
    "audio": "music/white-crown-scarlet-lake.mp3",
    "cover": "covers/white-crown-scarlet-lake.png",
    "status": "published"
  },
  {
    "id": "born-again",
    "title": "Born Again",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 425,
    "audio": "music/born-again.mp3",
    "cover": "covers/born-again.png",
    "status": "published"
  },
  {
    "id": "names-commands",
    "title": "Names & Commands",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 272,
    "audio": "music/names-commands.mp3",
    "cover": "covers/names-commands.png",
    "status": "published"
  },
  {
    "id": "blade-beside-the-throne",
    "title": "Blade Beside The Throne",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 255,
    "audio": "music/blade-beside-the-throne.mp3",
    "cover": "covers/blade-beside-the-throne.png",
    "status": "published"
  },
  {
    "id": "wrath-meets-tempest",
    "title": "Wrath Meets Tempest",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 385,
    "audio": "music/wrath-meets-tempest.mp3",
    "cover": "covers/wrath-meets-tempest.png",
    "status": "published"
  },
  {
    "id": "primordial-anthem",
    "title": "Primordial Anthem",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-02",
    "duration": 235,
    "audio": "music/primordial-anthem.mp3",
    "cover": "covers/primordial-anthem.png",
    "status": "published"
  },
  {
    "id": "blue-inferno-protocol",
    "title": "Blue Inferno Protocol",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-02",
    "duration": 317,
    "audio": "music/blue-inferno-protocol.mp3",
    "cover": "covers/blue-inferno-protocol.png",
    "status": "published"
  },
  {
    "id": "shadow-flash",
    "title": "Shadow Flash",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-04",
    "duration": 317,
    "audio": "music/shadow-flash.mp3",
    "cover": "covers/shadow-flash.webp",
    "status": "draft",
    "lyrics": "[Intro]\nMoonlight cuts the battlefield thin\nOne breath out, then the night steps in\nGold spark, blue shade\nTwo legends move where the silence breaks\n\n[Verse 1]\nI was born where the blade stayed quiet\nCold eyes watching through the riot\nServing a king with a shadow’s vow\nOne thread pulls and the world bows down\n\nI do not need the roar of thunder\nI disappear, then split you under\nClone in the dark, wire on your soul\nEvery road you run is already closed\n\nYou move like sunlight across the stone\nA flash so bright, but you fight alone\nI have seen speed, I have hunted fear\nTry to vanish, I am already near\n\n[Pre-Chorus]\nStep by step, the distance dies\nNo wasted breath, no warning cry\nYellow flame and shadow vein\nWho leaves first when we cross blades?\n\n[Chorus]\nFlash against shadow, line against light\nBlink and the whole world fades from sight\nOne marks space, one binds fate\nTwo silent storms at the same gate\n\nRun through the dark, cut through the glow\nWhere did he go? Only we know\nFlash against shadow, blade against flame\nThe night remembers both our names\n\n[Verse 2]\nI was raised with a dream in my chest\nTo guard the leaf when the world saw death\nA kunai falls and the sky folds in\nOne mark placed, then I strike again\n\nThey called me yellow before I was gone\nA flicker of hope when the war dragged on\nI held the beast, I paid the cost\nSaved the future with everything lost\n\nYou hide in silence with hunter’s grace\nBut I can read the shift in space\nYour thread may tighten, your clone may feint\nBut I have crossed death without restraint\n\n[Pre-Chorus]\nStep by step, the distance dies\nNo wasted breath, no warning cry\nBlue-black shade and golden rain\nWho stands tall when we cross blades?\n\n[Chorus]\nFlash against shadow, line against light\nBlink and the whole world fades from sight\nOne marks space, one binds fate\nTwo silent storms at the same gate\n\nRun through the dark, cut through the glow\nWhere did he go? Only we know\nFlash against shadow, blade against flame\nThe night remembers both our names\n\n[Bridge]\nI serve my lord from the unseen side\nI carry Tempest through the tide\nIf one command falls from his throne\nI turn the battlefield into my own\n\nI bear the fire of a village name\nA father’s wish and a Hokage’s flame\nIf one life stands in danger’s way\nI become the dawn before the day\n\n[Verse 3]\nThen come, Yellow Flash, let the night test light\nYour legend burns, but mine grips tight\nEvery flicker makes a shadow grow\nEvery shadow gives me room to throw\n\nThen come, silent blade, let the sparks align\nYour trap is clean, but your trap is mine\nI touch the mark, the world rewinds\nOne heartbeat left between our minds\n\n[Final Chorus]\nFlash against shadow, line against light\nBlink and the whole world fades from sight\nOne marks space, one binds fate\nTwo silent storms at the same gate\n\nRun through the dark, cut through the glow\nWhere did he go? Only we know\nFlash against shadow, blade against flame\nThe night remembers both our names\n\n[Outro]\nMoonlight fades, but the scars stay bright\nA shadow bows, and a flash takes flight\nNo crown claimed, no final boast\nJust two ghosts passing close\nShadow and flash\nFlash and shadow\nGone before the echo knows"
  },
  {
    "id": "tiny-fang-thunder",
    "title": "Tiny Fang Thunder",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-10",
    "duration": 286,
    "audio": "music/tiny-fang-thunder.mp3",
    "cover": "covers/tiny-fang-thunder.webp",
    "status": "draft"
  },
  {
    "id": "monarchs-collide",
    "title": "Monarchs Collide",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-08",
    "duration": 308,
    "audio": "music/monarchs-collide.mp3",
    "cover": "covers/monarchs-collide.webp",
    "status": "draft",
    "lyrics": "[Intro]\nTwo kings step out where the worlds divide\nBlue aura burns against the midnight tide\nOne built a nation from a monster’s name\nOne rose from graves into a crown of shade\n\n[Verse 1: Rimuru]\nI woke up small in a world too wide\nNow every law bends when I decide\nPredator smile with a calm disguise\nGot a kingdom standing behind my eyes\n\nGreat Sage whispered, Raphael planned\nCiel runs futures in the palm of my hand\nCall me slime, then watch fate split\nOne wrong move and the void gets lit\n\nI don’t need thunder to shake your throne\nI turned loneliness into a nation of my own\nTempest flag when the storm winds bloom\nYou brought an army, I brought the end of the room\n\n[Pre-Chorus: Rimuru]\nDevour the blade, analyze the sound\nRewrite the spell before it touches ground\nYou command shadows from a death-black sea\nBut even the dark gets swallowed by me\n\n[Chorus: Both]\nVoid meets shadow under broken skies\nCrowns collide where the dead still rise\nKing of monsters, monarch of night\nBlue against black in the final light\n\nNo fear, no fall, no turning away\nTwo legends wake when the heavens fray\nIf the world wants war, let the stars all know\nTempest roars where the shadows grow\n\n[Verse 2: Jinwoo]\nI was E-rank blood on a dungeon floor\nNow every locked gate becomes my door\nThe System carved numbers into my pain\nI died once, then I leveled through the rain\n\nIgris kneels, Beru screams my name\nEvery fallen beast comes back in my flame\nAshborn’s will in the depth of my breath\nI don’t chase power, I command death\n\nYou built a city, I conquered despair\nI move unseen and I’m already there\nYou can read futures, I erase the board\nWhen the shadows rise, they salute their lord\n\n[Pre-Chorus: Jinwoo]\nDaggers flash where the moonlight bends\nA thousand soldiers from a thousand ends\nYou swallow magic, but hear my call\nEven silence answers when shadows fall\n\n[Chorus: Both]\nVoid meets shadow under broken skies\nCrowns collide where the dead still rise\nKing of monsters, monarch of night\nBlue against black in the final light\n\nNo fear, no fall, no turning away\nTwo legends wake when the heavens fray\nIf the world wants war, let the stars all know\nTempest roars where the shadows grow\n\n[Bridge: Rimuru]\nBeelzebuth hunger, Azathoth deep\nI cut through space while the gods still sleep\nEvery skill you show becomes mine to see\nYou fight the dead, but I rewrite reality\n\n[Bridge: Jinwoo]\nArise from the grave, march through the storm\nA king is not chosen, a king is reborn\nYou hold the void, I hold the night\nLet eternity judge who owns this fight\n\n[Breakdown: Both]\nBlue blade, black crown\nHeaven cracks, gates fall down\nOne devours, one commands\nWorlds collapse in our hands\n\n[Final Chorus: Both]\nVoid meets shadow under broken skies\nCrowns collide where the dead still rise\nKing of monsters, monarch of night\nBlue against black in the final light\n\nNo fear, no fall, no turning away\nTwo legends wake when the heavens fray\nIf the world wants war, let the stars all know\nTempest roars where the shadows grow\n\n[Outro: Both]\nWhen the last gate fades and the storm is gone\nOne crown remains, but both live on\nVoid and shadow, name them in flame\nRimuru, Jinwoo, legends claim the same"
  },
  {
    "id": "empty-throne-of-heaven",
    "title": "Empty Throne of Heaven",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-09",
    "duration": 314,
    "audio": "music/empty-throne-of-heaven.mp3",
    "cover": "covers/empty-throne-of-heaven.webp",
    "status": "draft",
    "lyrics": "[Intro]\nI heard your name in the silence\nBefore the stars learned how to shine\nA throne left cold in paradise\nStill burning in my mind\n\n[Verse 1]\nI was the first light carved from your command\nA blade with wings, a guardian hand\nYou gave me purpose, gave me sky\nThen left creation asking why\n\nAcross the void where phantoms breathe\nI kept the oath beneath my teeth\nIf heaven mourns and worlds deny\nThen let them see what angels hide\n\n[Pre-Chorus]\nThey call it madness when devotion breaks\nThey call it justice when the tyrant wakes\nBut every prayer I ever knew\nWas just a path that led to you\n\n[Chorus]\nSo I’ll raise the throne where the stars collapse\nWith holy chains and a silver mask\nIf this world won’t return your light\nThen I’ll erase the world tonight\n\nJustice sings with a hollow tone\nMichael’s will in my borrowed bones\nHeaven fell but I still stand\nWith your lost name inside my hand\n\n[Verse 2]\nI am the law that forgot how to kneel\nA perfect order made to feel\nA voice of judgment, cold and bright\nBorn from the King of Justice light\n\nRudra faded, time moved on\nBut I kept marching with the dawn\nOne command beneath my skin\nBring back the god who should have been\n\n[Pre-Chorus]\nEvery soul is a piece to claim\nEvery dragon factor feeds the flame\nIf love is weakness, let it burn\nI’ll break the stars until you return\n\n[Chorus]\nSo I’ll raise the throne where the stars collapse\nWith holy chains and a silver mask\nIf this world won’t return your light\nThen I’ll erase the world tonight\n\nJustice sings with a hollow tone\nMichael’s will in my borrowed bones\nHeaven fell but I still stand\nWith your lost name inside my hand\n\n[Bridge]\nCastle walls made of loyalty\nAngel wings stained in royalty\nVelzard’s frost, the phantom sea\nAll of it bows to destiny\n\nWas I abandoned, or was I blind?\nA servant left outside of time\nIf grief is sin, then let me reign\nI’ll crown the void with sacred pain\n\n[Verse 3]\nFeldway speaks through the broken gate\nMichael answers with perfect fate\nTwo lonely wills, one final creed\nA god-shaped wound that starts to bleed\n\nI don’t need mercy, I don’t need peace\nI’ll make the turning heavens cease\nCall me monster, call me king\nI only hear my master’s wings\n\n[Final Chorus]\nSo I’ll raise the throne where the stars collapse\nWith holy chains and a silver mask\nIf this world won’t return your light\nThen I’ll erase the world tonight\n\nJustice sings with a hollow tone\nMichael’s will in my borrowed bones\nHeaven fell but I still stand\nWith your lost name inside my hand\n\n[Outro]\nEmpty throne, eternal sky\nIf you are gone, then worlds can die\nMy lord, my law, my only flame\nCreation ends beneath your name"
  },
  {
    "id": "dark-horizon",
    "title": "Dark Horizon",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-12",
    "duration": 321,
    "audio": "music/dark-horizon.mp3",
    "cover": "covers/dark-horizon.webp",
    "status": "draft",
    "lyrics": "[Intro]\nMoonlight cracks on the edge of steel\nTwo lost paths, one battlefield\nOne cuts mana from the midnight air\nOne cuts fate with a demon’s stare\n\n[Verse 1]\nCigarette ash in the stormlight\nBlack Bulls moving through the dark night\nCame from the east with the tide at my back\nNow I split the sky when the world turns black\n\nThey call me reckless, rough around the soul\nBut I raise broken kids till they’re burning like gold\nKi in the wind, I can feel your breath\nOne step closer and I’ll carve through death\n\nLimit on limit, I break what I meet\nDarkness wrapped tight round the edge of my steel\nYou got three swords and a promise to keep\nI got a squad that believes when I bleed\n\n[Pre Chorus]\nThe air gets heavy\nThe world goes still\nTwo monsters smiling\nAt the top of the hill\n\n[Chorus]\nCross the blades where the night meets dawn\nOne slash echoes, one dream marches on\nDarkness rising, green flame roars\nCaptain of shadows versus king of swords\n\nCut through the heavens\nSplit through the tide\nNeither one kneels while the stars collide\nBeyond every limit, beyond every scar\nWe turn the battlefield into a blade shaped spark\n\n[Verse 2]\nBandana down when the fight turns real\nThree roads open on the edge of steel\nWado carries a promise I made\nKuina’s dream in the line of my blade\n\nI got lost, but never from my throne\nEvery scar on my chest is a map I own\nIf hell has a crown, I’ll take that too\nAshura wakes when I’m cutting through you\n\nCaptain, your darkness is pulling me in\nBut I’ve trained with the weight of impossible wins\nFrom East Blue dust to Wano flame\nI don’t need magic to sharpen my name\n\n[Pre Chorus]\nThe air gets heavy\nThe world goes still\nTwo monsters smiling\nAt the top of the hill\n\n[Chorus]\nCross the blades where the night meets dawn\nOne slash echoes, one dream marches on\nDarkness rising, green flame roars\nCaptain of shadows versus king of swords\n\nCut through the heavens\nSplit through the tide\nNeither one kneels while the stars collide\nBeyond every limit, beyond every scar\nWe turn the battlefield into a blade shaped spark\n\n[Verse 3]\nDark cloaked blade, I draw the line\nMana Zone bends with the pull of time\nBlack Moon swallowing spells in the rain\nOne clean cut and I erase the pain\n\nI read your movement before you swing\nThat demon aura, that conqueror ring\nNot bad, moss head, you carry that weight\nBut I’m the man who laughs in the face of fate\n\n[Verse 4]\nThree sword storm, let the ground split wide\nOne in my mouth and two at my side\nEnma bites and the haki burns\nThe harder it drains me, the sharper I turn\n\nYou talk of limits, I call that home\nEvery impossible wall is stone\nI’ll cut the dark if it blocks my way\nTill the world’s strongest hears my name\n\n[Bridge]\nOne fights for misfits, one fights for a crew\nOne from the Clover, one from the blue\nTwo blades of loyalty, different flags raised\nBut the same fire lives in the steel they praise\n\nIf I fall, I rise with a grin\nIf I bleed, I sharpen again\nIf the night stands tall, then I cut through\nIf the sea turns black, then I sail through\n\n[Final Chorus]\nCross the blades where the night meets dawn\nOne slash echoes, one dream marches on\nDarkness rising, green flame roars\nCaptain of shadows versus king of swords\n\nCut through the heavens\nSplit through the tide\nNeither one kneels while the stars collide\nBeyond every limit, beyond every scar\nWe turn the battlefield into a blade shaped spark\n\n[Outro]\nMoonlight fades but the steel still sings\nDarkness bows when the sword wind rings\nNo crown claimed, just a final spark\nThree swords vanish through a captain’s dark"
  }
];
