// Managed by Xotiic Upload. Only complete releases are shown publicly.
window.XOTIICDUCK_RELEASES = [
  {
    "id": "void-crown-treasury",
    "title": "Void Crown Treasury",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 306,
    "audio": "music/void-crown-treasury.mp3",
    "cover": "covers/void-crown-treasury.png",
    "status": "published"
  },
  {
    "id": "beyond-the-last-tomorrow",
    "title": "Beyond The Last Tomorrow",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 480,
    "audio": "music/beyond-the-last-tomorrow.mp3",
    "cover": "covers/beyond-the-last-tomorrow.png",
    "status": "published"
  },
  {
    "id": "silent-storm",
    "title": "Silent Storm",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 418,
    "audio": "music/silent-storm.mp3",
    "cover": "covers/silent-storm.png",
    "status": "published"
  },
  {
    "id": "ghost-of-the-uchiha",
    "title": "Ghost Of The Uchiha",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 326,
    "audio": "music/ghost-of-the-uchiha.mp3",
    "cover": "covers/ghost-of-the-uchiha.png",
    "status": "published"
  },
  {
    "id": "storm-dragon-unleashed",
    "title": "Storm Dragon Unleashed",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 332,
    "audio": "music/storm-dragon-unleashed.mp3",
    "cover": "covers/storm-dragon-unleashed.png",
    "status": "published"
  },
  {
    "id": "tempest-garage",
    "title": "Tempest Garage",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 345,
    "audio": "music/tempest-garage.mp3",
    "cover": "covers/tempest-garage.png",
    "status": "published"
  },
  {
    "id": "misfit-crown",
    "title": "Misfit Crown",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 315,
    "audio": "music/misfit-crown.mp3",
    "cover": "covers/misfit-crown.png",
    "status": "published"
  },
  {
    "id": "rise",
    "title": "Rise",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 282,
    "audio": "music/rise.mp3",
    "cover": "covers/rise.png",
    "status": "published"
  },
  {
    "id": "earthquake",
    "title": "Earthquake",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 447,
    "audio": "music/earthquake.mp3",
    "cover": "covers/earthquake.png",
    "status": "published"
  },
  {
    "id": "the-little-world-queen",
    "title": "The Little World Queen",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 298,
    "audio": "music/the-little-world-queen.mp3",
    "cover": "covers/the-little-world-queen.png",
    "status": "published"
  },
  {
    "id": "sleeping-ruler",
    "title": "Sleeping Ruler",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 290,
    "audio": "music/sleeping-ruler.mp3",
    "cover": "covers/sleeping-ruler.png",
    "status": "published"
  },
  {
    "id": "twilight-valentine",
    "title": "Twilight Valentine",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 337,
    "audio": "music/twilight-valentine.mp3",
    "cover": "covers/twilight-valentine.png",
    "status": "published"
  },
  {
    "id": "platinum-fallen",
    "title": "Platinum Fallen",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 300,
    "audio": "music/platinum-fallen.mp3",
    "cover": "covers/platinum-fallen.png",
    "status": "published"
  },
  {
    "id": "starborn-catastrophe",
    "title": "Starborn Catastrophe",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 432,
    "audio": "music/starborn-catastrophe.mp3",
    "cover": "covers/starborn-catastrophe.png",
    "status": "published"
  }
];
