// Managed by Xotiic Upload. Only complete releases are shown publicly.
window.XOTIICDUCK_RELEASES = [
  {
    "id": "void-crown-treasury",
    "title": "Void Crown Treasury",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 306,
    "audio": "music/void-crown-treasury.mp3",
    "cover": "covers/void-crown-treasury.png",
    "status": "published"
  },
  {
    "id": "beyond-the-last-tomorrow",
    "title": "Beyond The Last Tomorrow",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 480,
    "audio": "music/beyond-the-last-tomorrow.mp3",
    "cover": "covers/beyond-the-last-tomorrow.png",
    "status": "published"
  },
  {
    "id": "silent-storm",
    "title": "Silent Storm",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 418,
    "audio": "music/silent-storm.mp3",
    "cover": "covers/silent-storm.png",
    "status": "published"
  },
  {
    "id": "ghost-of-the-uchiha",
    "title": "Ghost Of The Uchiha",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 326,
    "audio": "music/ghost-of-the-uchiha.mp3",
    "cover": "covers/ghost-of-the-uchiha.png",
    "status": "published"
  },
  {
    "id": "storm-dragon-unleashed",
    "title": "Storm Dragon Unleashed",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 332,
    "audio": "music/storm-dragon-unleashed.mp3",
    "cover": "covers/storm-dragon-unleashed.png",
    "status": "published"
  },
  {
    "id": "tempest-garage",
    "title": "Tempest Garage",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 345,
    "audio": "music/tempest-garage.mp3",
    "cover": "covers/tempest-garage.png",
    "status": "published"
  },
  {
    "id": "misfit-crown",
    "title": "Misfit Crown",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 315,
    "audio": "music/misfit-crown.mp3",
    "cover": "covers/misfit-crown.png",
    "status": "published"
  },
  {
    "id": "rise",
    "title": "Rise",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 282,
    "audio": "music/rise.mp3",
    "cover": "covers/rise.png",
    "status": "published",
    "lyrics": "[Intro]\nFrom another world, I opened my eyes\nA tiny blue spark under foreign skies\nA voice in my soul began to rise\nGreat Sage, guide me through the night\n\n[Verse 1]\nI woke as a slime where the wild winds roam\nCold cave walls became my home\nThen thunder laughed from a prison of stone\nVeldora, the storm, stood alone\n\nWe traded names beneath the dark\nTempest burned like a newborn mark\nA dragon’s vow and a slime’s first start\nTwo souls carrying one fierce heart\n\n[Pre-Chorus]\nI swallowed the fear, I learned to transform\nTurned every scar into shelter from storms\nFrom weakest of legends to ruler reborn\nI’ll build tomorrow with these hands\n\n[Chorus]\nRise, Tempest, rise\nLet the banners touch the sky\nFor every monster cast aside\nI’ll be the name they call with pride\n\nShine, silver light\nMask of fate and demon eyes\nFrom slime to king, from dusk to dawn\nRimuru Tempest carries on\n\n[Verse 2]\nShizu’s flame was fading slow\nA hero’s sorrow I came to know\nHer mask, her wish, her gentle glow\nBecame the face I’d never throw\n\nGoblin, wolf, ogre, kijin flame\nI gave them hope, I gave them names\nIn Jura’s forest we rose the same\nA nation born from bonds, not chains\n\n[Pre-Chorus]\nBenimaru’s fire, Shuna’s prayer\nSouei moving through midnight air\nShion’s blade and Ranga’s glare\nAll of Tempest standing there\n\n[Chorus]\nRise, Tempest, rise\nLet the banners touch the sky\nFor every monster cast aside\nI’ll be the name they call with pride\n\nShine, silver light\nMask of fate and demon eyes\nFrom slime to king, from dusk to dawn\nRimuru Tempest carries on\n\n[Post-Chorus]\nOh-oh, Great Sage awaken\nOh-oh, Raphael calling\nOh-oh, my vow unshaken\nTempest will rise\n\n[Verse 3]\nWhen my people fell, the sky went still\nMercy bent beneath my will\nMegiddo rained with judgment’s chill\nA king must guard what monsters built\n\nThe Harvest came with crimson light\nTen thousand souls crossed into night\nA Demon Lord opened his eyes\nAnd Raphael answered from inside\n\n[Bridge]\nGluttony roars, Beelzebuth devours\nUriel shields my promised towers\nVeldora’s storm becomes my power\nI stand for peace in the darkest hour\n\nI’ll face the saints, the lords, the throne\nThe world may test the path I own\nBut every soul that calls Tempest home\nWill never stand alone\n\n[Final Chorus]\nRise, Tempest, rise\nLet the banners touch the sky\nFor every monster cast aside\nI’ll be the name they call with pride\n\nShine, silver light\nMask of fate and demon eyes\nFrom slime to king, from dusk to dawn\nRimuru Tempest carries on\n\n[Outro]\nFrom a cave to a kingdom bright\nFrom a slime to a storm in flight\nIf this world wants peace, I’ll be the light\nRimuru Tempest, born to unite"
  },
  {
    "id": "earthquake",
    "title": "Earthquake",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 447,
    "audio": "music/earthquake.mp3",
    "cover": "covers/earthquake.png",
    "status": "published"
  },
  {
    "id": "the-little-world-queen",
    "title": "The Little World Queen",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 298,
    "audio": "music/the-little-world-queen.mp3",
    "cover": "covers/the-little-world-queen.png",
    "status": "published"
  },
  {
    "id": "sleeping-ruler",
    "title": "Sleeping Ruler",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 290,
    "audio": "music/sleeping-ruler.mp3",
    "cover": "covers/sleeping-ruler.png",
    "status": "published"
  },
  {
    "id": "twilight-valentine",
    "title": "Twilight Valentine",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 337,
    "audio": "music/twilight-valentine.mp3",
    "cover": "covers/twilight-valentine.png",
    "status": "published"
  },
  {
    "id": "platinum-fallen",
    "title": "Platinum Fallen",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 300,
    "audio": "music/platinum-fallen.mp3",
    "cover": "covers/platinum-fallen.png",
    "status": "published"
  },
  {
    "id": "starborn-catastrophe",
    "title": "Starborn Catastrophe",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 432,
    "audio": "music/starborn-catastrophe.mp3",
    "cover": "covers/starborn-catastrophe.png",
    "status": "published"
  },
  {
    "id": "red-fang-promise",
    "title": "Red Fang Promise",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 396,
    "audio": "music/red-fang-promise.mp3",
    "cover": "covers/red-fang-promise.png",
    "status": "published"
  },
  {
    "id": "crimson-axis",
    "title": "Crimson Axis",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 343,
    "audio": "music/crimson-axis.mp3",
    "cover": "covers/crimson-axis.png",
    "status": "published"
  },
  {
    "id": "oath-of-noir",
    "title": "Oath Of Noir",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 316,
    "audio": "music/oath-of-noir.mp3",
    "cover": "covers/oath-of-noir.png",
    "status": "published"
  },
  {
    "id": "violet-verdict",
    "title": "Violet Verdict",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 319,
    "audio": "music/violet-verdict.mp3",
    "cover": "covers/violet-verdict.png",
    "status": "published"
  },
  {
    "id": "gold-collapse",
    "title": "Gold Collapse",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 346,
    "audio": "music/gold-collapse.mp3",
    "cover": "covers/gold-collapse.png",
    "status": "published"
  },
  {
    "id": "white-crown-scarlet-lake",
    "title": "White Crown, Scarlet Lake",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 310,
    "audio": "music/white-crown-scarlet-lake.mp3",
    "cover": "covers/white-crown-scarlet-lake.png",
    "status": "published"
  },
  {
    "id": "born-again",
    "title": "Born Again",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 425,
    "audio": "music/born-again.mp3",
    "cover": "covers/born-again.png",
    "status": "published"
  },
  {
    "id": "names-commands",
    "title": "Names & Commands",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 272,
    "audio": "music/names-commands.mp3",
    "cover": "covers/names-commands.png",
    "status": "published"
  },
  {
    "id": "blade-beside-the-throne",
    "title": "Blade Beside The Throne",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 255,
    "audio": "music/blade-beside-the-throne.mp3",
    "cover": "covers/blade-beside-the-throne.png",
    "status": "published"
  },
  {
    "id": "wrath-meets-tempest",
    "title": "Wrath Meets Tempest",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-01",
    "duration": 385,
    "audio": "music/wrath-meets-tempest.mp3",
    "cover": "covers/wrath-meets-tempest.png",
    "status": "published"
  },
  {
    "id": "primordial-anthem",
    "title": "Primordial Anthem",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-02",
    "duration": 235,
    "audio": "music/primordial-anthem.mp3",
    "cover": "covers/primordial-anthem.png",
    "status": "published"
  },
  {
    "id": "blue-inferno-protocol",
    "title": "Blue Inferno Protocol",
    "artist": "XotiicDuck",
    "album": "Single",
    "genre": "Anime J-Rock",
    "releaseDate": "2026-08-02",
    "duration": 317,
    "audio": "music/blue-inferno-protocol.mp3",
    "cover": "covers/blue-inferno-protocol.png",
    "status": "published"
  }
];
